apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infra
  namespace: dev
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/cloud-first-approach/Evolution.infra

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: dev
spec:
  interval: 1m0s
  path: ./deploy/k8s/infra/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra