apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shopcart-api
  namespace: dev
  annotations:
    backstage.io/kubernetes-id: "ShopCart.Api"
spec:
  interval: 1m0s
  path: ./deploy/k8s/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: shopcart-api
