apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dot_api_1
  namespace: dev
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kubeosx/dot_api_1