apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app1
  namespace: dev
spec:
  interval: 1m0s
  path: 
  prune: true
  sourceRef:
    kind: GitRepository
    name: app1