apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: stock-api
  namespace: dev
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/iamsourabh-in/stock-api